# Generated by Django 4.0 on 2021-12-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0012_prdodutreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrdodutReview',
            new_name='ProductReview',
        ),
    ]
