# Generated by Django 4.0 on 2021-12-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_prdodutreview_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='starts',
            new_name='stars',
        ),
    ]
