# Generated by Django 4.0 on 2021-12-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_fist_name_order_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
            preserve_default=False,
        ),
    ]
