# Generated by Django 4.0 on 2021-12-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_ordenitem_orden_ordenitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
